### ISSUE TITLE
isScanning not valid and  .WhenScanningStatusChanged() only fired once

### ISSUE THREAD

**Issue by x37v** [aritchie/bluetoothle#145] opened 2018-03-02 23:30 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
android 7.0

## Version of Library
git master and 5.3.2

## Expected Behaviour

`BleAdapter.IsScanning` should reflect scanning status
 `WhenScanningStatusChanged()` should fire when scanning changes

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

a break point here:
https://github.com/aritchie/bluetoothle/blob/master/Samples/Samples/ViewModels/Le/ScanViewModel.cs#L40

only hits once after it is observed, giving *false*

a break point at the above line as well as here:
https://github.com/aritchie/bluetoothle/blob/master/Samples/Samples/ViewModels/Le/ScanViewModel.cs#L83
indicates that `BleAdapter.IsScanning` is always *false*

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment] 2018-03-02 23:36
Duplicate of #105

**Closed by aritchie** 2018-03-02 23:36 UTC
