### ISSUE TITLE
[Bug] 6.2.5 Scan Error for Android 9

### ISSUE THREAD

**Issue by hudaIT** [aritchie/bluetoothle#321] opened 2019-07-15 20:26 UTC
I have these permissions in my manfiest

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
```
I have the 6.2.5 version of the nuget in my xamarin.forms and in my xamarin.android project installed

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ X] Android
 - [ ] UWP
 - [ X] .NET Standard

## Version of Library
6.2.5
## Version of OS(s) listed above with issue
Android 9.0

## Steps to Reproduce
1. Create blank Xamarin forms project
2. Try to Scan => Plugin.BluetoothLE.CrossBleAdapter.Current.Scan();
3. Finished

## Expected Behavior
Scan for devices

## Actual Behavior
No platform Plugin found
![NoPlugin](https://user-images.githubusercontent.com/51824173/61246616-8ceb5a00-a74f-11e9-9c1f-e38e7de4cc10.PNG)

Example below.
[BluetoothTestFail.zip](https://github.com/aritchie/bluetoothle/files/3394092/BluetoothTestFail.zip)
#319

**Comment by aritchie** [comment] 2019-07-15 20:38
Duplicate of #319

**Closed by aritchie** 2019-07-15 20:38 UTC
