### ISSUE TITLE
GetKnownCharacteristics() hangs on initially retrieved value

### ISSUE THREAD

**Issue by cpboyd** [aritchie/bluetoothle#46] opened 2017-05-31 13:26 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS

## Version of OS(s) listed above with issue
Tested on iOS 10.3.2

## Version of Library
3.1.1

## Expected Behaviour
I should be able to request and retrieve multiple characteristics, one after another, without issue.

## Actual Behavior
```c#
            currentDevice = (await ScanForDevices().FirstAsync(result => result.Device.Uuid == uuid)).Device;
            await currentDevice.Connect();
            var service = await currentDevice.GetKnownService(DeviceService);
            var rxChar = await service.GetKnownCharacteristics(DeviceRx).FirstAsync();
            var txChar = await service.GetKnownCharacteristics(DeviceTx).FirstAsync();
            var notif = txChar.SubscribeToNotifications();
```

This results in both `rxChar` and `txChar` containing **identical** characteristics (corresponding to `DeviceService`/`DeviceRx`), even though the specified UUID is different.

As a result, `SubscribeToNotifications()` throws an error because `DeviceRx` only allows writes, thus providing no notifications.

If I comment out the `var rxChar` line, then `txChar` represents the proper characteristic and no error gets thrown.

**Comment by cpboyd** [comment] 2017-05-31 13:45
Workarounds:
```c#
var temp = await currentDevice.GetKnownCharacteristics(DeviceService, DeviceRx, FlirTx).ToList();
            foreach (var x in temp) {
				if (x.Uuid == DeviceRx)
				{
					rxChar = x;
				}
				else if (x.Uuid == FlirTx)
				{
					var notif = x.SubscribeToNotifications();
					if (onConnect != null)
					{
						notif = notif.Do(_ => onConnect());
					}
					notif.Subscribe(result =>
					{
						var str = Encoding.ASCII.GetString(result.Data);
						Console.WriteLine(str);
						responseSubject.OnNext(str);
					}).DisposeWith(subList);
				}
            }
```

or

```c#
            currentDevice.GetKnownCharacteristics(DeviceService, DeviceRx, FlirTx).Subscribe(x => {
				if (x.Uuid == DeviceRx)
				{
					rxChar = x;
				}
				else if (x.Uuid == FlirTx)
				{
					var notif = x.SubscribeToNotifications();
					if (onConnect != null)
					{
						notif = notif.Do(_ => onConnect());
					}
					notif.Subscribe(result =>
					{
						var str = Encoding.ASCII.GetString(result.Data);
						Console.WriteLine(str);
						responseSubject.OnNext(str);
					}).DisposeWith(subList);
				}
            }).DisposeWith(subList);
```

**Comment by aritchie** [comment] 2017-05-31 14:37
That isn't really a workaround.  That is how I intended it to work.

It should be able to handle consecutive calls.  I'll look into this for a future release.

**Comment by aritchie** [comment] 2017-10-29 18:38
no feedback and cant reproduce - closing

**Closed by aritchie** 2017-10-29 18:38 UTC
Labels: bug, in-progress
